[project]
name = "happy"
version = "0.1.0"
description = ""
authors = [
    {name = "HippoMaiDinh",email = "hoangviet6131@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]

[tool.poetry]
packages = [{include = "happy", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
